# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1


# =================================
# = Datasource
# =================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/jobby?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/jobby?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

# =================================
# = Logging
# =================================
logging:
  level:
    org.springframework: INFO
    org.flywaydb: INFO

# =================================
# = Swagger
# =================================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: org.generation.app_hopemarket.controller
