--CREATE TABLE `jobby`.`tb_endereco` (
--  `id`          INT NOT NULL AUTO_INCREMENT,
--  `cep`         INT NOT NULL,
--  `logradouro`  VARCHAR(255) NOT NULL,
--  `numero`      VARCHAR(10) NOT NULL,
--  `complemento` VARCHAR(255) NOT NULL,
--  `bairro`      VARCHAR(255) NOT NULL,
--  PRIMARY KEY (`id`)
-- );
